parameters:
    cisco.spark.oauth.class:       CiscoSystems\SparkBundle\Authentication\Oauth
    cisco.spark.room.class:        CiscoSystems\SparkBundle\Event\Room
    cisco.spark.membership.class:  CiscoSystems\SparkBundle\Event\Membership
    cisco.spark.messages.class:    CiscoSystems\SparkBundle\Event\Messages
    cisco.spark.people.class:      CiscoSystems\SparkBundle\Event\People
    cisco.spark.webhooks.class:    CiscoSystems\SparkBundle\Event\WebHooks
    cisco.spark.class:             CiscoSystems\SparkBundle\Spark
    
services:
    cisco.spark.oauth:
        class: '%cisco.spark.oauth.class%'
        arguments:
            - '%cisco.spark.config%'
            - '@doctrine.orm.entity_manager'
    cisco.spark.room:
        class: '%cisco.spark.room.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.membership:
        class: '%cisco.spark.membership.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.message:
        class: '%cisco.spark.messages.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.people:
        class: '%cisco.spark.people.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.webhook:
        class: '%cisco.spark.webhooks.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark:
        class: '%cisco.spark.class%'
        arguments:
            - '@cisco.spark.room'
            - '@cisco.spark.membership'
            - '@cisco.spark.message'
            - '@cisco.spark.people'
            - '@cisco.spark.webhook'
   