parameters:
    cisco.spark.oauth.class:          CiscoSystems\SparkBundle\Authentication\Oauth
    cisco.spark.room.class:           CiscoSystems\SparkBundle\Event\Room
    cisco.spark.team.class:           CiscoSystems\SparkBundle\Event\Team
    cisco.spark.membership.class:     CiscoSystems\SparkBundle\Event\Membership
    cisco.spark.teammembership.class: CiscoSystems\SparkBundle\Event\TeamMembership
    cisco.spark.message.class:        CiscoSystems\SparkBundle\Event\Message
    cisco.spark.people.class:         CiscoSystems\SparkBundle\Event\People
    cisco.spark.webhook.class:        CiscoSystems\SparkBundle\Event\WebHook
    cisco.spark.class:                CiscoSystems\SparkBundle\Common\Spark
    
services:
    cisco.spark.oauth:
        class: '%cisco.spark.oauth.class%'
        arguments:
            - '%cisco.spark.config%'
            - '@doctrine.orm.entity_manager'
    cisco.spark.room:
        class: '%cisco.spark.room.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.team:
        class: '%cisco.spark.team.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.membership:
        class: '%cisco.spark.membership.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.teammembership:
        class: '%cisco.spark.teammembership.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.message:
        class: '%cisco.spark.message.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.people:
        class: '%cisco.spark.people.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark.webhook:
        class: '%cisco.spark.webhook.class%'
        arguments:
            - '@cisco.spark.oauth'
    cisco.spark:
        class: '%cisco.spark.class%'
        arguments:
            - '@cisco.spark.room'
            - '@cisco.spark.team'
            - '@cisco.spark.membership'
            - '@cisco.spark.teammembership'
            - '@cisco.spark.message'
            - '@cisco.spark.people'
            - '@cisco.spark.webhook'
            - '@cisco.spark.oauth'
   